# relative paths
region_evaluated_dir: dataset/region/evaluated
output_dir: dataset/rgb/mandelbrot/twilight_res1024_iter1024
job_type: rgb
fractal_type: mandelbrot
colormap: twilight_shifted

hires_gen:
  width: 1024
  height: 1024
  max_iter: 1024
  use_supersampling: true
  device: cuda
