# relative paths
region_evaluated_dir: dataset/region/evaluated
rgb_root_dir: dataset/rgb
job_type: rgb
colormap_group: curated_colormaps

hires_gen:
  width: 1024
  height: 1024
  max_iter: 1024
  use_supersampling: true
  device: cuda
